grpc:
    host: "127.0.0.1"
    port: 9999
    enable: false

http:
    host: "127.0.0.1"
    port: 9988
    enable: true

db:
    pathtodb: "./"
    namedb: "links.db"

tg:
    Token: "token"
    AllowedIDs:
        - "1"
        - "2"
    Admins:
        - "3"
    ProxyPool:
        - ""
