// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: docs/proto/v1/bot.proto

// Имя пакета

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterDownloaderRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerName       string                 `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	AllowedRootLinks []string               `protobuf:"bytes,2,rep,name=allowedRootLinks,proto3" json:"allowedRootLinks,omitempty"`
	ServerHost       string                 `protobuf:"bytes,3,opt,name=serverHost,proto3" json:"serverHost,omitempty"`
	ServerPort       int32                  `protobuf:"varint,4,opt,name=serverPort,proto3" json:"serverPort,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterDownloaderRequest) Reset() {
	*x = RegisterDownloaderRequest{}
	mi := &file_docs_proto_v1_bot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDownloaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDownloaderRequest) ProtoMessage() {}

func (x *RegisterDownloaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_bot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDownloaderRequest.ProtoReflect.Descriptor instead.
func (*RegisterDownloaderRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_bot_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterDownloaderRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *RegisterDownloaderRequest) GetAllowedRootLinks() []string {
	if x != nil {
		return x.AllowedRootLinks
	}
	return nil
}

func (x *RegisterDownloaderRequest) GetServerHost() string {
	if x != nil {
		return x.ServerHost
	}
	return ""
}

func (x *RegisterDownloaderRequest) GetServerPort() int32 {
	if x != nil {
		return x.ServerPort
	}
	return 0
}

var File_docs_proto_v1_bot_proto protoreflect.FileDescriptor

const file_docs_proto_v1_bot_proto_rawDesc = "" +
	"\n" +
	"\x17docs/proto/v1/bot.proto\x12\agrpc.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xa7\x01\n" +
	"\x19RegisterDownloaderRequest\x12\x1e\n" +
	"\n" +
	"serverName\x18\x01 \x01(\tR\n" +
	"serverName\x12*\n" +
	"\x10allowedRootLinks\x18\x02 \x03(\tR\x10allowedRootLinks\x12\x1e\n" +
	"\n" +
	"serverHost\x18\x03 \x01(\tR\n" +
	"serverHost\x12\x1e\n" +
	"\n" +
	"serverPort\x18\x04 \x01(\x05R\n" +
	"serverPort2Y\n" +
	"\x03Bot\x12R\n" +
	"\x12RegisterDownloader\x12\".grpc.v1.RegisterDownloaderRequest\x1a\x16.google.protobuf.Empty\"\x00B\x0fZ\rdocs/proto/v1b\x06proto3"

var (
	file_docs_proto_v1_bot_proto_rawDescOnce sync.Once
	file_docs_proto_v1_bot_proto_rawDescData []byte
)

func file_docs_proto_v1_bot_proto_rawDescGZIP() []byte {
	file_docs_proto_v1_bot_proto_rawDescOnce.Do(func() {
		file_docs_proto_v1_bot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_proto_v1_bot_proto_rawDesc), len(file_docs_proto_v1_bot_proto_rawDesc)))
	})
	return file_docs_proto_v1_bot_proto_rawDescData
}

var file_docs_proto_v1_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_docs_proto_v1_bot_proto_goTypes = []any{
	(*RegisterDownloaderRequest)(nil), // 0: grpc.v1.RegisterDownloaderRequest
	(*emptypb.Empty)(nil),             // 1: google.protobuf.Empty
}
var file_docs_proto_v1_bot_proto_depIdxs = []int32{
	0, // 0: grpc.v1.Bot.RegisterDownloader:input_type -> grpc.v1.RegisterDownloaderRequest
	1, // 1: grpc.v1.Bot.RegisterDownloader:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_docs_proto_v1_bot_proto_init() }
func file_docs_proto_v1_bot_proto_init() {
	if File_docs_proto_v1_bot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_v1_bot_proto_rawDesc), len(file_docs_proto_v1_bot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_v1_bot_proto_goTypes,
		DependencyIndexes: file_docs_proto_v1_bot_proto_depIdxs,
		MessageInfos:      file_docs_proto_v1_bot_proto_msgTypes,
	}.Build()
	File_docs_proto_v1_bot_proto = out.File
	file_docs_proto_v1_bot_proto_goTypes = nil
	file_docs_proto_v1_bot_proto_depIdxs = nil
}
